name: Publish Package to NPM

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Kunci utama bypass 2FA & Token
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Menggunakan Node 24 terbaru
          registry-url: 'https://npmjs.org'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Publish to NPM
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Menggunakan Token Internal GitHub

